### ISSUE TITLE
User feature request tracker

### ISSUE THREAD

**Issue by hjonnala** [org-jonnala/lab#68]
- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:

**Comment by hjonnala** [comment]
- [ ] Add delight to the experience when all tasks are complete :tada2:
